import {
  AutonomousCurriculumPlanner,
  type CurriculumTask,
} from "./autonomous-curriculum";

import {
  CompetenceModel,
  type CompetenceObservation,
  type CompetenceSnapshot,
} from "./competence-model";

import {
  EvaluationIsolationGuard,
  type GatedSequenceChallengeSpec,
} from "./synthetic-challenge";

export interface GatedSequenceChallengeBlueprint {
  family:
    string;

  kind:
    "gated-sequence";

  minDifficulty:
    number;

  maxDifficulty:
    number;

  estimatedCost:
    number;

  prerequisiteFamilies?:
    string[];

  practiceActionLabels:
    readonly [
      string,
      string,
      string,
    ];

  practiceStateKeys:
    readonly [
      string,
      string,
      string,
    ];

  practiceActionRoleOrder:
    readonly [
      0 | 1 | 2,
      0 | 1 | 2,
      0 | 1 | 2,
    ];
}

export interface GeneratedPracticeChallenge {
  spec:
    GatedSequenceChallengeSpec;

  curriculumScore:
    number;

  reasons:
    string[];

  familyCompetence:
    CompetenceSnapshot;
}

function clamp(
  value:
    number,

  minimum:
    number,

  maximum:
    number,
): number {
  return Math.max(
    minimum,
    Math.min(
      maximum,
      value,
    ),
  );
}

function validateBlueprint(
  blueprint:
    GatedSequenceChallengeBlueprint,
): void {
  if (
    !blueprint.family
      .trim()
  ) {
    throw new Error(
      "Challenge family must be non-empty.",
    );
  }

  for (
    const [
      label,
      value,
    ] of [
      [
        "minDifficulty",
        blueprint.minDifficulty,
      ],
      [
        "maxDifficulty",
        blueprint.maxDifficulty,
      ],
    ] as const
  ) {
    if (
      !Number.isFinite(
        value,
      ) ||
      value <
        0 ||
      value >
        1
    ) {
      throw new Error(
        "Challenge blueprint " +
        label +
        " must be between 0 and 1.",
      );
    }
  }

  if (
    blueprint.minDifficulty >
    blueprint.maxDifficulty
  ) {
    throw new Error(
      "Challenge blueprint minimum difficulty cannot exceed maximum difficulty.",
    );
  }

  if (
    !Number.isFinite(
      blueprint.estimatedCost,
    ) ||
    blueprint.estimatedCost <
      0
  ) {
    throw new Error(
      "Challenge blueprint estimated cost must be non-negative.",
    );
  }

  if (
    new Set(
      blueprint
        .practiceActionLabels,
    ).size !==
      3
  ) {
    throw new Error(
      "Practice action labels must be unique.",
    );
  }

  if (
    new Set(
      blueprint
        .practiceStateKeys,
    ).size !==
      3
  ) {
    throw new Error(
      "Practice state keys must be unique.",
    );
  }

  const roles = [
    ...blueprint
      .practiceActionRoleOrder,
  ].sort();

  if (
    roles[0] !==
      0 ||
    roles[1] !==
      1 ||
    roles[2] !==
      2
  ) {
    throw new Error(
      "Practice action roles must be a permutation of 0, 1, and 2.",
    );
  }
}

function safeFamilyId(
  family:
    string,
): string {
  const normalized =
    family
      .toLowerCase()
      .replace(
        /[^a-z0-9]+/g,
        "-",
      )
      .replace(
        /^-+|-+$/g,
        "",
      );

  return normalized ||
    "challenge";
}

/**
 * Mabojolu G autonomous safe challenge generator v0.1.
 *
 * The generator chooses among approved synthetic challenge blueprints, but the
 * individual practice task is generated by Mabojolu from current competence
 * evidence. Evaluation-partition tasks cannot be emitted by this class.
 */
export class AutonomousChallengeGenerator {
  private readonly planner:
    AutonomousCurriculumPlanner;

  private readonly generationCounts =
    new Map<
      string,
      number
    >();

  constructor(
    private readonly competence:
      CompetenceModel,

    private readonly isolation:
      EvaluationIsolationGuard,

    private readonly blueprints:
      readonly GatedSequenceChallengeBlueprint[],
  ) {
    if (
      blueprints.length ===
      0
    ) {
      throw new Error(
        "At least one safe challenge blueprint is required.",
      );
    }

    for (
      const blueprint of
        blueprints
    ) {
      validateBlueprint(
        blueprint,
      );
    }

    this.planner =
      new AutonomousCurriculumPlanner(
        competence,
      );
  }

  generateNextPractice():
    GeneratedPracticeChallenge |
    undefined {
    const candidates:
      CurriculumTask[] =
      this.blueprints.map(
        (blueprint) => {
          const snapshot =
            this.competence
              .snapshot(
                blueprint.family,
              );

          const difficulty =
            clamp(
              snapshot.mastery +
                0.2,

              blueprint
                .minDifficulty,

              blueprint
                .maxDifficulty,
            );

          const generatedCount =
            this.generationCounts
              .get(
                blueprint.family,
              ) ??
            0;

          const novelty =
            Math.max(
              0.5,
              1 -
                generatedCount *
                  0.08,
            );

          return {
            id:
              "generate::" +
              blueprint.family,

            family:
              blueprint.family,

            difficulty,

            novelty,

            estimatedCost:
              blueprint
                .estimatedCost,

            ...(blueprint
                .prerequisiteFamilies
              ? {
                  prerequisiteFamilies: [
                    ...blueprint
                      .prerequisiteFamilies,
                  ],
                }
              : {}),
          };
        },
      );

    const recommendation =
      this.planner
        .chooseNext(
          candidates,
        );

    if (
      !recommendation
    ) {
      return undefined;
    }

    const blueprint =
      this.blueprints.find(
        (candidate) =>
          candidate.family ===
          recommendation
            .task
            .family,
      );

    if (
      !blueprint
    ) {
      return undefined;
    }

    const nextGeneration =
      (
        this.generationCounts
          .get(
            blueprint.family,
          ) ??
        0
      ) +
      1;

    this.generationCounts
      .set(
        blueprint.family,
        nextGeneration,
      );

    const familyId =
      safeFamilyId(
        blueprint.family,
      );

    const spec:
      GatedSequenceChallengeSpec = {
      id:
        "practice-" +
        familyId +
        "-" +
        nextGeneration,

      family:
        blueprint.family,

      kind:
        "gated-sequence",

      partition:
        "practice",

      difficulty:
        recommendation
          .task
          .difficulty,

      context:
        "generated-practice-" +
        familyId +
        "-" +
        nextGeneration,

      actionLabels: [
        ...blueprint
          .practiceActionLabels,
      ],

      stateKeys: [
        ...blueprint
          .practiceStateKeys,
      ],

      actionRoleOrder: [
        ...blueprint
          .practiceActionRoleOrder,
      ],
    };

    this.isolation
      .registerPractice(
        spec,
      );

    return {
      spec,

      curriculumScore:
        recommendation.score,

      reasons: [
        ...recommendation
          .reasons,
      ],

      familyCompetence:
        recommendation
          .familyCompetence,
    };
  }

  recordPracticeOutcome(input: {
    challenge:
      GatedSequenceChallengeSpec;

    success:
      boolean;

    cycles:
      number;

    observedAt:
      string;
  }):
    CompetenceSnapshot {
    if (
      input.challenge
        .partition !==
      "practice"
    ) {
      throw new Error(
        "Only practice challenge outcomes may update the autonomous training competence model.",
      );
    }

    const observation:
      CompetenceObservation = {
      taskId:
        input.challenge
          .id,

      family:
        input.challenge
          .family,

      difficulty:
        input.challenge
          .difficulty,

      success:
        input.success,

      cycles:
        input.cycles,

      observedAt:
        input.observedAt,
    };

    return this.planner
      .recordOutcome(
        observation,
      );
  }

  getGenerationCount(
    family:
      string,
  ):
    number {
    return this
      .generationCounts
      .get(
        family,
      ) ??
      0;
  }
}
