/**
 * Mabojolu G cognitive state contracts.
 *
 * These types deliberately separate:
 *
 * observation -> belief -> hypothesis -> goal -> action -> outcome -> learning
 *
 * The cognitive kernel must be able to explain which evidence caused a belief
 * or hypothesis to change. That provenance is essential for reproducible
 * experiments and later long-term learning.
 */

export type CognitiveId = string;

export type Confidence = number;

export type ObservationSource =
  | "environment"
  | "user"
  | "tool"
  | "self";

export interface Observation {
  id: CognitiveId;

  source: ObservationSource;

  /**
   * What Mabojolu directly observed.
   *
   * An observation is evidence, not an interpretation.
   */
  content: string;

  observedAt: string;

  metadata?: Record<
    string,
    string | number | boolean | null
  >;
}

export type BeliefStatus =
  | "active"
  | "retracted";

export interface Belief {
  id: CognitiveId;

  /**
   * A proposition Mabojolu currently considers likely to be true.
   */
  proposition: string;

  confidence: Confidence;

  status: BeliefStatus;

  /**
   * Evidence that currently supports this belief.
   */
  evidenceIds: CognitiveId[];

  updatedAt: string;
}

export type HypothesisStatus =
  | "candidate"
  | "supported"
  | "rejected";

export interface Hypothesis {
  id: CognitiveId;

  /**
   * A testable explanation or predicted relationship.
   */
  statement: string;

  confidence: Confidence;

  status: HypothesisStatus;

  evidenceFor: CognitiveId[];

  evidenceAgainst: CognitiveId[];

  createdAt: string;

  updatedAt: string;
}

export type GoalStatus =
  | "pending"
  | "active"
  | "completed"
  | "blocked"
  | "abandoned";

export interface Goal {
  id: CognitiveId;

  description: string;

  /**
   * 0 = lowest priority
   * 100 = highest priority
   */
  priority: number;

  status: GoalStatus;

  /**
   * Explicit evidence that proves the goal has been achieved.
   */
  successCriteria: string[];

  /**
   * Rules that must remain true while pursuing this goal.
   */
  constraints: string[];

  parentGoalId?: CognitiveId;

  /**
   * Goals that must be satisfied before this goal can become actionable.
   */
  dependsOnGoalIds?: CognitiveId[];

  /**
   * Why this goal cannot currently proceed.
   */
  blockedReason?: string;

  /**
   * When a blocked or abandoned branch is replanned, the replacement keeps an
   * auditable link to the branch it supersedes.
   */
  replacementForGoalId?: CognitiveId;

  createdAt: string;

  updatedAt: string;
}

export interface ActionProposal {
  id: CognitiveId;

  /**
   * Machine-readable action category.
   *
   * Examples:
   * inspect
   * test
   * move
   * search
   * calculate
   * ask
   */
  kind: string;

  description: string;

  /**
   * What Mabojolu predicts will happen if this action is taken.
   */
  expectedEffects: string[];

  /**
   * 0 = negligible risk
   * 1 = maximum modeled risk
   */
  risk: number;

  reversible: boolean;

  /**
   * Some actions may eventually require human approval.
   */
  requiresApproval: boolean;

  createdAt: string;
}

export type ActionStatus =
  | "proposed"
  | "selected"
  | "executing"
  | "completed"
  | "failed"
  | "cancelled";

export interface ActionRecord {
  id: CognitiveId;

  proposal: ActionProposal;

  status: ActionStatus;

  selectedAt?: string;

  completedAt?: string;
}

export interface Outcome {
  id: CognitiveId;

  actionId: CognitiveId;

  success: boolean;

  /**
   * New observations generated by the action.
   */
  observationIds: CognitiveId[];

  summary: string;

  recordedAt: string;
}

export type LearningKind =
  | "rule"
  | "strategy"
  | "correction"
  | "skill";

export interface LearningRecord {
  id: CognitiveId;

  kind: LearningKind;

  /**
   * Generalized knowledge extracted from experience.
   */
  statement: string;

  confidence: Confidence;

  /**
   * Observations, outcomes, hypotheses, or beliefs from which this learning
   * was derived.
   */
  derivedFromIds: CognitiveId[];

  createdAt: string;
}

export interface CognitiveState {
  /**
   * Schema version for future migration and experiment replay.
   */
  version: 1;

  /**
   * One completed observe/reason/act/learn iteration increments this value.
   */
  cycle: number;

  observations: Observation[];

  beliefs: Belief[];

  hypotheses: Hypothesis[];

  goals: Goal[];

  actions: ActionRecord[];

  outcomes: Outcome[];

  learnings: LearningRecord[];

  activeGoalId?: CognitiveId;

  createdAt: string;

  updatedAt: string;
}

/**
 * Every cognitive state transition is represented explicitly as an event.
 *
 * This gives Mabojolu G an auditable cognitive history that can later be
 * persisted and replayed during experiments.
 */
export type CognitiveEvent =
  | {
      type: "observation.recorded";
      observation: Observation;
    }
  | {
      type: "belief.updated";
      belief: Belief;
    }
  | {
      type: "hypothesis.updated";
      hypothesis: Hypothesis;
    }
  | {
      type: "goal.updated";
      goal: Goal;
    }
  | {
      type: "goal.activated";
      goalId: CognitiveId;
      occurredAt: string;
    }
  | {
      type: "action.updated";
      action: ActionRecord;
    }
  | {
      type: "outcome.recorded";
      outcome: Outcome;
    }
  | {
      type: "learning.recorded";
      learning: LearningRecord;
    }
  | {
      type: "cycle.advanced";
      occurredAt: string;
    };