import "server-only";

import { deriveTitle } from "@/lib/utilities/ids";

/**
 * Conversation titles.
 *
 * Deliberately derived from the first user message rather than generated by a
 * second model call. A generated title costs an extra billable request per
 * conversation and adds latency to the first reply, for a string the user can
 * rename in one click. That is a poor trade at this stage.
 *
 * The heuristics below produce a usefully specific title in the common cases: a
 * question, an instruction, or a topic. `generateConversationTitle` is the seam
 * where a model-generated title would slot in later without changing callers.
 */

/**
 * Words carrying no distinguishing information at the start of a request.
 *
 * Stripping them turns "Can you help me write a business plan" into "Write a
 * business plan", which is what a user scanning a sidebar actually needs.
 */
const LEADING_FILLER = [
  "can you please",
  "can you",
  "could you please",
  "could you",
  "would you please",
  "would you",
  "please help me",
  "please",
  "help me to",
  "help me",
  "i need you to",
  "i need help with",
  "i need to",
  "i want you to",
  "i want to",
  "i would like to",
  "id like to",
  "i'd like to",
  "hey mabojolu",
  "hi mabojolu",
  "hello mabojolu",
  "mabojolu",
  "tell me about",
  "explain to me",
  "let me know",
];

export function generateConversationTitle(firstUserMessage: string): string {
  const cleaned = stripFiller(collapseWhitespace(firstUserMessage));

  if (cleaned.length === 0) {
    // Falls back rather than producing an empty sidebar entry.
    return deriveTitle(firstUserMessage);
  }

  // Prefer the first sentence. A long first paragraph makes a poor label, and the
  // opening sentence is almost always the actual request.
  const sentence = firstSentence(cleaned);
  const candidate = sentence.length >= 12 ? sentence : cleaned;

  return capitalize(deriveTitle(candidate, 48));
}

function collapseWhitespace(value: string): string {
  // Code blocks and pasted text carry newlines and runs of spaces that would
  // otherwise produce a ragged title.
  return value.replace(/\s+/g, " ").trim();
}

function stripFiller(value: string): string {
  let result = value;

  // Repeat until stable, because requests often stack politeness: "Hi Mabojolu,
  // could you please help me write..."
  let changed = true;
  while (changed) {
    changed = false;
    const lower = result.toLowerCase();

    for (const filler of LEADING_FILLER) {
      if (lower.startsWith(`${filler} `)) {
        result = result.slice(filler.length + 1).trim();
        changed = true;
        break;
      }
    }

    // Drop a leading comma left behind by a stripped greeting.
    const trimmed = result.replace(/^[,:\-\s]+/, "");
    if (trimmed !== result) {
      result = trimmed;
      changed = true;
    }
  }

  return result;
}

function firstSentence(value: string): string {
  // Requires whitespace after the terminator, so "3.5" and "e.g." do not split.
  const match = /^(.{12,}?[.!?])(\s|$)/.exec(value);
  return match ? match[1].trim() : value;
}

function capitalize(value: string): string {
  if (value.length === 0) {
    return value;
  }

  // Leave an already-capitalized or non-alphabetic start alone, so an acronym
  // such as "SQL joins explained" is not mangled.
  const first = value[0];
  if (first !== first.toLowerCase()) {
    return value;
  }

  return first.toUpperCase() + value.slice(1);
}
